### ISSUE TITLE
P1. ImageManager: "Create your own puzzle" 

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#12]
Load image from device into a "custom puzzle" Resources folder in game.
Essentially the player can create their own puzzles from their own photos.

**Comment by TimChroma** [comment]
Any estimates for the amount of effort this task is btw?

**Comment by ByteSheep** [comment]
Shouldn't be too much work really, main problem is letting the player choose an image from their gallery. Haven't looked into it, but there should be plugins for that if Unity doesn't support it out of the box :)

**Comment by TimChroma** [comment]
OK cool - I didn't find anything obvious in the asset store, but I'll take another look. Happy to buy a solution ofc, please just let me know which one you think looks best :)

**Comment by ByteSheep** [comment]
This git repo looks like it might do the trick: https://github.com/thedoritos/unimgpicker
I'll probably try importing it tomorrow :)

**Comment by TimChroma** [comment]
awesome awesome. I've been swamped with my parents in town this weekend/week hence the no commits. but i'll be skinning, bug fixing, and setting up asset bundles at the weekend. jfyi :)

**Comment by ByteSheep** [comment]
I've been working on this a little bit and think I have the basic functionality of importing an image to the Resources folder working, though I haven't been able to test this on a device.
One of the main things I'm unsure of is how the UI for this should work - should your custom puzzles be accessible in the pack selection panel? Is this what the MyCollection pack would be used for or is that meant to used for something else? :)

**Comment by TimChroma** [comment]
Awesome - I will dig in tonight. SOrry, I haven't been home this weekend yet, but will get the signing keys to you asap. 

Good point on the UI - I will create a new pack for createdPuzzles + associated flow menus etc. (MyCollection will contain any unlocked puzzle, including created puzzles)

**Comment by TimChroma** [comment]
Keystore: Signing Key Chroma 2 109

Alias: PKSkey
Alias PW: Chroma PKSkey 880

**Comment by ByteSheep** [comment]
A basic implementation should now be working: the player can select an image from their device and optionally the image can be saved to the Resources folder :)

**Comment by TimChroma** [comment]
Thanks Ariel! Loading/creating a single puzzle works great! However, when I uncomment the AddImageToCollection code, it no longer works (tapping "Create Puzzle" button goes to a blank difficulty menu). The player should be able to play the puzzle and it also be added to MyCollection with all other unlocked puzzles.

**Comment by TimChroma** [comment]
Ack - I also broke the script moving it from the CustomButton to a CustomPopup. What OnClick events do I need to use? Sorry man

**Comment by TimChroma** [comment]
Yay! Works on device. Marking down to a P3 (Nice to have) because I still need to play with saving-custom-puzzle to Resources.

**Comment by TimChroma** [comment]
Saving to Resources code breaks this whole feature when this part is uncommented. Any ideas? Would be great to have fixed cos it's a key feature

**Comment by ByteSheep** [comment]
I'll have to take a look into it tomorrow :) It seems part of the problem is that it's trying to save the file to a directory that no longer exists (Resources/Custom Puzzles), but overall the trickiest part is still changing the puzzle selection code to be more flexible so that you can display different things there depending upon which pack you selected

**Comment by ByteSheep** [comment]
I've pushed some changes that should fix the saving to Resources issue - not quite done yet though, since the image picker currently isn't shown anymore. Will try to fix that tomorrow (just a question of where the player should click to choose to load a new image) ;)

**Comment by TimChroma2** [comment]
Added a button to open the image picker, but the puzzle isn't created when an image is shown any more. Tested on a device

**Comment by ByteSheep** [comment]
Sorry this is taking so long, will try to get this done by tonight :)

**Comment by TimChroma** [comment]
Issues: 

1. Using Application.persistentDataPath: DirectoryNotFoundException: Could not find a part of the path "/Users/wooga/Library/Application Support/Chroma2/PuzzleKings/Resources/CustomPuzzles/Image_2018-01-23_12-13-43-PM.png".

2. I'm not sure where to set customImage as image to load into puzzle.

**Comment by TimChroma** [comment]
Moving to next version.
