### ISSUE TITLE
Screenshotter tech bugs

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#18]
- Screenshotter/WinMenu not resetting after first round (on device only; seems to work in editor) 
- Possible to take repeated screenshots, which looks dumb (fix: just hide the button after being used)

**Comment by TimChroma** [comment]
Can be removed if needed

**Comment by TimChroma** [comment]
IEnumerator getScreenshot() //make bounds = pictOver dimensions

**Comment by TimChroma** [comment]
Not sure if I fixed it properly, or got lucky with some preset values. Anyway, ready for testing, preferably on a few devices with different screen sizes/ratios.

**Comment by TimChroma2** [comment]
Fixed
