### ISSUE TITLE
Remove index from reference used to check unlocked state of a pack or a puzzle

### ISSUE THREAD

**Issue by smartmike** [PuzzleKing/puzzle-king#22]
This isn't very future proof, as soon as something changes which changes the order of the paths, or the puzzles, the reference will be off. Suggest simply changing to image name for a pack, and folder + image name for a puzzle. This will at least stop it breaking if something is added in between or before other packs/puzzles. Even better would be a unique ID that isn't tied to folder name or image name, but that's not 100% needed.

**Comment by TimChroma** [comment]
What's the priority on this then? Sounds like a nice-to-have, but not necessarily essential for MVP?

**Comment by smartmike** [comment]
Well, if you launch without this you're gonna have a bad time changing it later, and it will fuck you for a long time
