### ISSUE TITLE
Packs not locked

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#25]
Packs should be able to be locked/unlocked. I guess we lost this in packSelection refactoring? 

If a pack is locked, it should show the lockedIcon + price, and tapping it should open the UnlockPopup

UPDATE: I notice the Pack Lock script is commented out in GameStarter, which I assume is relevant to this. I tried to enable it again, but packs still were not locked. I guess the way we check has changed? I re-commented out the Pack Lock code in Game Starter FYI

**Comment by TimChroma2** [comment]
Packs can be locked/unlocked now \o/
