### ISSUE TITLE
Ads not being triggered consistenly correctly (UPDATED)

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#31]
Ads need to actually play now

**Comment by TimChroma** [comment]
Ads CAN be triggered from unlock popups, but need to work on the UI a bit. 

- Always make sure RequestAd() is called 5 secs before ShowAd()
- Disable PlayAd button if no ad loaded
- Freeze UI until ad is started (so players can't tap through menus before ad is shown)
- Show interstitial after results screen (TBC)

**Comment by TimChroma2** [comment]
Works. Need an info popup/script if no wifi/ad found, but thats another UI/UX issue
