### ISSUE TITLE
Game economy

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#35]
Content rules: 

- 3 packs with 10 puzzles completely free (Jan - Mar)
- 9 other packs in v1.0 (Apr - Dec), each containing:
> Per pack
>> 3x "Preview" puzzles (watch ad to play each, or unlock individually for 100* coins each)
>> 17x "Premium" puzzles (watch ad to play each, or pay 1000* coins to unlock entire pack)
>>> If pack unlocked, no need to watch ads or pay for rest of pack (mark all as unlocked)

*Coin prices TBD. Balance against expected coin earns etc
** Indicate 'free' + 'premium' content in UI

**Comment by TimChroma** [comment]
Optional: implement "Piggy Bank feature". 

- Coins from connecting pieces go into Piggy Bank
- Opening Piggy Bank is a $10 IAP, irregardless of how much is in it
- So we need:
> 2 HUDs: "Coins Owned" and "Piggy Bank"
> Piggy Bank detached from CoinHUD
> Win 10-25 coins for completing a puzzle (depending on difficulty) (to CoinHUD)
> IAP for Piggy Bank
> Piggy Bank logic 
>>IAP $10 = PB contents at any given time
>> Reset Piggy Bank

**Comment by TimChroma** [comment]
Piggy Bank WIP: Players now win 10 Coins per completed puzzle

**Comment by TimChroma2** [comment]
Piggy Bank IAP in; a couple of bugs in current version; I will fix these tomorrow

**Comment by TimChroma** [comment]
Need to add some logic for when PiggyBank balance = 0 (player should not be able to purchase in this case). But I will do that with other Store logic

**Comment by TimChroma** [comment]
TODO: 

- Apply economy balancing from doc
- Cannot purchase PiggyBank if PiggyBalance = 0 
- UnlockAll popup + logic when purchasing with coins
- New IAPs packages (and removeBanners)
- Finish Store UI including discount offers
- QuickBuy PiggyBank button
- Color code UI for free/premium, locked/unlocked etc
- Unlock all packs as default
- Watch ad for playing CustomPuzzle

**Comment by TimChroma** [comment]
Moved outstanding issues to master list
