### ISSUE TITLE
Daily puzzle

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#38]
How much GD effort is this really, now assetbundles are up and running...?

**Comment by TimChroma2** [comment]
Tasks for daily puzzle:

> 365(!) (or whatever) unique puzzles on server under an asset bundle ("Daily Puzzles"), using DateTime naming conventions
> Preview panel with 'mystery' icon, as we won't have the actual image to display on app open
>> Next version: Download today's thumbnail on app load
> Play button downloads asset
>> Need to send DateTime name to asset bundle name to get the right one
> Notification scheduled for new puzzle

**Comment by TimChroma** [comment]
NAMING CONVENTION: 

AssetBundleName = DailyPuzzle
AssetName = "18-01-15" (YY-MM-DD)

**Comment by TimChroma** [comment]
TODO: 

- Send Daily Puzzle to Difficulty Selection (allow skipping of puzzle menu; load game straight from Pack Selection in this special case)
- Trigger notification every day
- Turn NEW sticker on/off as appropriate

**Comment by TimChroma** [comment]
Moved last tasks to Outstanding Issues master list
