### ISSUE TITLE
ImageManager: Min/Max sizes of resources/images not supported 

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#4]
There is currently a max size that fits nicely on to the game board. If the original image is too big it will not be possible to see/connect the pieces in the game view). 

Is it possible to resize/scale large/small images to fit within the game board? This should be able to handle all sizes/dimensions/ratios without distorting the image

**Comment by TimChroma** [comment]
I guess that's referring to this in board_puzzle.cs

	public void Initialize()
	{
		sizeBoardX = piecesX;
		sizeBoardY = piecesY;

		pictBack.localScale = new Vector3(image.width, image.height, 1);
		pictOver.localScale = pictBack.localScale;

		sizeCellX = (int)pictBack.localScale.x / sizeBoardX;
		sizeCellY = (int)pictBack.localScale.y / sizeBoardY;
		dockValue = Mathf.Min(sizeCellX, sizeCellY) / 4;

**Comment by TimChroma** [comment]
Big images already looking better - they fit into the screen space at least. There needs to be some space around the edges of the max sized board (for loose pieces). I think the size/scale of the Peacock puzzle work quite nicely as a reference

**Comment by ByteSheep** [comment]
I believe this issue is solved, but if not feel free to reopen it and I'll take another look :)
