### ISSUE TITLE
Oustanding issues

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#40]
~3. Loading spinner STILL not animating on splash/loading screen (loadingtext.cs, Start scene)
- UniShareTakeImage.ShareText update with tinyurl + #puzzlekings 
- Remove debug options throughout menus for RC, inc test notifications, skippable ads, ad calls, dash settings etc
- Resolve error messages, missing refs, repeated ad requests etc
- Product Marketing https://getemoji.com/#activities~

**Comment by TimChroma** [comment]
LOOK HOW SHORT THE LIST IS!!! \o/

**Comment by TimChroma** [comment]
So unless some miracle happens, I'm gonna have to cut custom puzzles for tomorrow's launch :/ Keep me posted if you have anything. But let's get beer!

**Comment by ArielSchoch** [comment]
Pushed a fix for:
> Loading spinner STILL not animating on splash/loading screen (loadingtext.cs, Start scene)
Looks like the speed value was just set too high - changed from 200 to 0.5 for now :)

**Comment by TimChroma** [comment]
Nexus 7
Screen
7.02" 1920 x 1200 HD display (323 ppi)

Nexus 10
Screen
10.055" diagonal at 2560 x 1600 pixel resolution for 300 ppi

Both devices have a 16:10 aspect ratio, other 7 and 10 inch devices might have different aspect ratios though.

**Comment by TimChroma** [comment]
Aaaaand that's a go :D RC is in beta - will do a final check in the morning and push to Prod. Holy fuck :D
