### ISSUE TITLE
Image size fuckery

### ISSUE THREAD

**Issue by TimChroma** [PuzzleKing/puzzle-king#41]
Ariel, can you take a look at this please? I guess you know the image handling best - no idea what could have happened, so I'm scared to dig in more :| :| :| 

- If a puzzle is unlocked, it will be small (256)
- if a puzzle is locked, and has to be loaded from asset bundles, it will be huge (2048, I guess) but played on a camera setting sized for 256 (so it’s not possible to complete). AND the gamboard is configured to expect a 256 image (I believe). 
- ~In both cases, the images rendered are buggy AF, as if the resolution is super low - you’ll see what I mean. UPDATE: Oh wait, this is definitely compression settings 9of course). Looking into it now. ~
- If it's relevant to address with this issue, the in game board should scale to be ~max screen height

**Comment by ByteSheep** [comment]
I'm afraid I can't load any images currently on the master branch - I seem to get null reference errors due to the puzzleImage texture not being set in LoadAssets.cs

**Comment by TimChroma** [comment]
Figured this out - I had the compression set all wrong (duh). And I think I can solve the loadAssets issue + making the gameboard big AF too. I'll take this first thing in the morning and let you know if I get stuck. 

Git is still syncing my side (might be stuck). I'll try restarting it and pushing changes again

**Comment by TimChroma** [comment]
Fixed - LoadAssets now gets called onPuzzleSelect, instead of from UnlockedPopup. Not sure what issues this solution may bring, but it's working for now at least.
